# Generated by Django 4.2.3 on 2023-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('receivable', models.DecimalField(decimal_places=5, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=5, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rati', models.DecimalField(decimal_places=5, max_digits=10)),
                ('gold', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_balance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
