# Generated by Django 4.2.3 on 2023-07-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cash_in',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cash_out',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payable',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rati',
        ),
        migrations.RemoveField(
            model_name='account',
            name='receivable',
        ),
        migrations.CreateModel(
            name='BalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable', models.DecimalField(decimal_places=5, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=5, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rati', models.DecimalField(decimal_places=5, max_digits=10)),
                ('gold', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cash_balance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_report', to='inventory.account')),
                ('gold_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_gold_price', to='inventory.goldprice')),
            ],
        ),
    ]
