# Generated by Django 4.2.3 on 2023-07-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_goldprice_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancereport',
            name='cash_balance',
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='cash_in',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='cash_out',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
