# Generated by Django 4.2.3 on 2023-07-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_balancereport_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancereport',
            name='balance',
        ),
    ]
